### ISSUE TITLE
Python terminal

### ISSUE THREAD

**Issue by ximerkf** [ximerkf/Vanar_courses_py#2]
У меня питон из терминала не запускается. В чем может быть проблема? 

![Image20220719224020](https://user-images.githubusercontent.com/105169557/179834620-f9b461aa-8b71-4aa3-9053-8fcfab7afe87.png)

**Comment by dorinesinenco** [comment]
скорей всего в том что названия папок содержат кирилицу, попробуй скопировать этот же файл прямо на диск D и запустить оттуда
