### ISSUE TITLE
SyntaxError: (unicode error)

### ISSUE THREAD

**Issue by ximerkf** [ximerkf/Vanar_courses_py#3]
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 8-9: truncated \xXX escape

Я уже разобрался, что проблема была в том, что я использовал в строке direction = input("dir (a\d\x)> ") , \ - этот символ. Но могли бы вы объяснить, почему это возникает.

![image](https://user-images.githubusercontent.com/105169557/180651663-2eb8040a-e20a-42dc-9215-2538994937bc.png)

**Comment by dorinesinenco** [comment]
символ \ обозначает "начало спецсимвола" если после него следует код который нельзы преобразовать в символ - дает ошибку
чтобы выводить \ - надо перед ним поставить еще 1 -> \\
